server:
  port: 8080

spring:
  application:
    name: error-handling-poc

management:
  endpoints:
    web:
      exposure:
        include: '*'

resilience4j:
  circuitbreaker:
    instances:
      externalService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      externalService:
        maxAttempts: 3
        waitDuration: 1s

logging:
  structured:
    format:
      console: ecs